[tool.black]
line-length = 119
target-version = ['py39']

[tool.djlint]
profile = "django"
use_gitignore = true
# H017: Ignored because opposite of W3C validator recommendation.
ignore="D004,D018,H005,H006,H007,H008,H008,H010,H011,H012,H013,H014,H015,H016,H017,H019,H020,H021,H022,H023,H024,H025,H026,H029,H030,H031,H033,J004,J018,T002,T003,T027,T028,T032,T034,H017"

# Per file ignores
# We use these to make it possible to introduce the linting for all files, but without the need to fix everything at once.
# New files and new violations will throw errors and should be fixed.
# Over time, we should fix every file and remove it from the ignore list.


[tool.isort]
profile = "black"
extend_skip = ["network-api/media", "network-api/staticfiles"]
skip_gitignore = true
known_first_party = ["networkapi"]
